---
- name: Define java_packages.
  set_fact:
    java_packages: "java-1.8.0-openjdk"
  when: java_packages is not defined

- name: Ensure Java is installed.
  package:
    name: "{{ java_packages }}"
    state: present
    
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
