---
apache_daemon: httpd
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/httpd
apache_conf_path: /etc/httpd/conf.d
apache_log_path: /var/log/httpd

selinux_enabled: true

apache_packages:
  - httpd
  - httpd-devel
  - mod_ssl
  - openssh