---
- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ apache_packages | list }}"

- name: Ensure Apache is installed.
  package:
    name: "{{ apache_packages }}"
    state: present
    
- name: Allow Apache to listen on tcp ports.
  seport:
    ports:
      - "80"
      - "443"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled
  notify: restart apache
  
- name: Allow Apache to connect remote hosts.
  command: >
    /usr/sbin/setsebool -P httpd_can_network_connect 1
  when: selinux_enabled
  notify: restart apache

- name: Configure Apache.
  template:
    src: httpd.conf.j2
    dest: "{{ apache_server_root }}/conf/httpd.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  
- name: Configure virtual hosts.
  template:
    src: "{{ item.src }}"
    dest: "{{ apache_conf_path }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: hosts.conf.j2, dest: hosts.conf }
    - { src: ssl.conf.j2, dest: ssl.conf }
  notify: restart apache
    
- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: httpd
    state: started
    enabled: true