---
- name: Install APM server.
  package:
    name: "apm-server-{{ apm_server_version }}"
    state: present

- name: Create APM server configuration files.
  template:
    src: apm-server.yml.j2
    dest: "{{ apm_server_config_dir }}/apm-server.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart apm-server
  
- name: Copy APM server certs.
  copy:
    remote_src: yes
    src: "{{ elastic_certs_dir }}/{{ item }}"
    dest: "{{ apm_server_certs_dir }}/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "ca/ca.crt"
    - "{{ apm_server_name }}/{{ apm_server_name }}.crt"
    - "{{ apm_server_name }}/{{ apm_server_name }}.key"
  notify: restart apm-server
  
- name: Ensure APM server is started and enabled on boot.
  service:
    name: apm-server
    state: started
    enabled: true